"""Make from_account_id nullable

Revision ID: 9646238ac648
Revises: 9a7755f2cfe5
Create Date: 2025-04-12 02:22:32.626484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9646238ac648'
down_revision = '9a7755f2cfe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('from_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('from_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
